version: '3.5'


services:
    traefik:
        image: traefik:v2.5
        command:
            - --api.insecure=false
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --entrypoints.websecure.address=:443
            - --entrypoints.web.address=:80
            - --certificatesresolvers.myresolver.acme.httpchallenge=true
            - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
            - --certificatesresolvers.myresolver.acme.email=business@belamov.com
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt:/letsencrypt
    backend:
        hostname: backend
        image: docker.pkg.github.com/rehearsalsbooking/backend/backend:production
        restart: unless-stopped
        volumes:
            - .env.backend:/app/.env
            - ./data/storage/:/app/storage/
        depends_on:
            - db
        labels:
            - traefik.enable=true
            - traefik.http.routers.backend.rule=Host(`api.festic.ru`)
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.routers.backend.tls.certresolver=myresolver

    frontend:
        image: docker.pkg.github.com/rehearsalsbooking/frontend/frontend:production
        volumes:
            - frontend-volume:/frontend
        labels:
            - traefik.enable=true
            - traefik.http.routers.frontend.rule=Host(`festic.ru`)
            - traefik.http.routers.frontend.entrypoints=websecure
            - traefik.http.routers.frontend.tls.certresolver=myresolver

    db:
        image: postgres:alpine
        env_file:
            - .env
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

volumes:
    frontend-volume:
    backend-volume:
