version: '3.5'


services:
  backend:
    hostname: backend
    image: docker.pkg.github.com/rehearsalsbooking/backend/backend:production
    volumes:
      - .env.backend:/app/.env
      - ./data/storage/:/app/storage/
      - backend-volume:/app
    depends_on:
      - db

  frontend:
    image: docker.pkg.github.com/rehearsalsbooking/frontend/frontend:production
    volumes:
      - frontend-volume:/frontend

  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend-volume:/usr/share/nginx/html/frontend
      - backend-volume:/app
      - ./data/storage/:/app/storage/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/:/var/log/nginx
    depends_on:
      - frontend
      - backend
      - db

volumes:
  frontend-volume:
  backend-volume: