name: Deploy

on:
  workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 142.93.99.186
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir test
            cd ~/infrastructure
            git reset --hard
            git pull
            make deploy