name: Deploy

on:
  workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 142.93.99.186
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_SECRET}}
          username: ${{ secrets.SSH_USER }}
          debug: true
          script: |
            cd ~/infrastructure
            git reset --hard
            git pull
            make deploy
